### ISSUE TITLE
Estudo dos projetos anteriores

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#10]
Descrição

Revisar os antigos projetos 

Tarefas

- [x] Preparar uma lista dos projetos úteis para o tema atual.
- [x] Avaliar se o projeto pode ajudar o grupo

**Comment by joseandre25** [comment]
Os projetos anteriores da disciplina podem nos servir como **exemplo de organização**, por exemplo: Criação de issues, boards, organiação de branches e readme.
Em questão temática muito pouco, visto que esse semestre tem um escopo limitado ao querido diário.
Segue exemplo de um repositório bem organizado anterior da disciplina pra nos dar um norte: 
https://github.com/fga-eps-mds/2023.1-HEART-hub-fga-inovacao

**Comment by joseandre25** [comment]
**Projeto exemplo do Querido Diário que a professora mandou:** 

https://exoonero.org/sobre/

https://github.com/exoonero/extrator
