### ISSUE TITLE
Estudo do Scrum 

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#11]
Descrição

Estudo da metodologia ágil Scrum,e como podemos aplicar no projeto

Tarefas

- [x] Estudar o Scrum 
- [x] Documentar oque podemos aproveitar do Scrum

**Comment by RafaBonach** [comment]
Encontrei um site muito bacana que explica de forma resumida, mas explica bem o que é o scrum. 
https://medium.com/reprogramabr/scrum-um-breve-resumo-f051e1bc06d9

**Comment by gio221** [comment]
Fizemos um reunião em que o Rafael criou o MkDocs e fizemos a documentação do Scrum 
Reunião no dia 23/09 das 13:30 as 15:00
