### ISSUE TITLE
Adicionar documentação para o parser 

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#17]
Descrição:
Nossa equipe precisa criar uma documentação completa e detalhada para o parser de para facilitar o uso e a contribuição de outros desenvolvedores. Atualmente, a falta de documentação dificulta a compreensão de como o parser funciona e como os desenvolvedores podem usá-lo.

Tarefas:

- [x]  Escrever uma introdução explicando o propósito do parser e sua importância no projeto.

- [x] Descrever os requisitos de instalação e as dependências necessárias para usar o parser.

- [x]  Fornecer exemplos de uso do parser com casos de teste e exemplos práticos.

- [x]  Documentar os parâmetros de configuração e opções disponíveis para personalização.

- [x] Explicar o formato de saída gerado pelo parser e como os resultados podem ser usados.

- [x]  Incluir informações sobre como contribuir para o desenvolvimento do parser, como guias de estilo de código e processos de revisão de código.

- [x]  Garantir que a documentação esteja atualizada com relação à versão mais recente do parser.

**Comment by samarawwleticia** [comment]
Fiz o commit da documentação do parser na pasta docs.
