### ISSUE TITLE
Implementação em MK Docs do Perfis de Usuário

### ISSUE THREAD

**Issue by samarawwleticia** [unb-mds/2023-2-Squad07#23]
Esta issue está relacionada à melhoria da documentação do projeto e à implementação de perfis de usuário para tornar a documentação mais personalizada e relevante para os nossos usuários.

 

- [x] Configurar o ambiente de desenvolvimento local com MK Docs.
- [x] Procurar por implementações de grupos dos semestres passados.
- [x] Implementar nosso perfil de usuário.
- [x] Fazer o commit da documentação.

**Comment by gio221** [comment]
Essa issue foi repassada para o integrante José
