### ISSUE TITLE
Implementação em MK Docs das Personas

### ISSUE THREAD

**Issue by samarawwleticia** [unb-mds/2023-2-Squad07#26]
- [ ]  Configurar o ambiente de desenvolvimento local com MK Docs.
- [ ]  Procurar por implementações de grupos dos semestres passados.
- [ ]  Implementar as personas.
- [ ] Fazer o commit da documentação.

**Comment by gio221** [comment]
Essa issue foi repassada para o integrante José

**Comment by samarawwleticia** [comment]
Documentei em mkdocs as personas
