### ISSUE TITLE
Configuração do Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by RafaBonach** [unb-mds/2023-2-Squad07#3]
# Descrição
Esta issue tem como objetivo guiar a configuração do ambiente de desenvolvimento para facilitar o início do trabalho da equipe. Um ambiente bem configurado é crucial para garantir uma colaboração eficiente e a entrega de código de alta qualidade.

## Tarefas
- [x] #4
- [x] Baixar Git
- [x] Baixar VSCode e extensões
- [x] Baixar python3

**Comment by RafaBonach** [comment]
Já baixei o Ubuntu, o git, o VSCode e o python3

**Comment by samarawwleticia** [comment]
já baixei o ubuntu, o git, o vscode e o python3

**Comment by juliatakaki** [comment]
Tinha baixado Python, VS Code e Git, mas quando fui baixar o Ubuntu meu PC deu problema e está no conserto.

**Comment by gio221** [comment]
já baixei o ubuntu, o git, o vscode e o python3
