### ISSUE TITLE
 Aprendendo React, HTML e CSS

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#52]
Descrição:

Nesta issue, vamos dedicar um tempo para aprender e aprimorar nossas habilidades em React, HTML e CSS. O objetivo é criar um ambiente de aprendizado colaborativo e construtivo, onde os participantes podem compartilhar recursos, discutir problemas, fazer perguntas e trabalhar juntos para aprimorar suas habilidades nesses três pilares essenciais do desenvolvimento web.

Tarefas propostas:

- [x]    Estudos de React: Compartilhe tutoriais, livros, cursos online ou qualquer outro recurso que tenha encontrado útil ao aprender ou aprimorar suas habilidades em React. Discuta os conceitos-chave, como componentes, estado, props, roteamento, etc.
- [x]     HTML e CSS: Compartilhe dicas e truques para criar layouts eficazes com HTML e estilizar elementos com CSS. Discuta as melhores práticas, técnicas de responsividade e qualquer desafio que você tenha encontrado.
- [x] Estudo do HTML e css.

**Comment by gio221** [comment]
Estudei react e javascript com alguns cursos

**Comment by samarawwleticia** [comment]
Dei os primeiros passos em REACT e CSS fazendo um pequeno projeto de uma calculadora através de um tutorial do youtube, pesquisei sobre o que é possível fazer com essas ferramentas e estudei o site do exoonera.

**Comment by juliatakaki** [comment]
Comecei a estudar react, JavaScript, html e css, pois acho importante ter toda essa base de conhecimento.

**Comment by juliatakaki** [comment]
Vi videoaulas e implementei um código mais simples para aplicar os conhecimentos adquiridos.
