### ISSUE TITLE
 Estudo do Uso do Scrapy para Pesquisar em todos os Diários Oficiais automaticamente

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#66]
Descrição:

Esta issue tem como objetivo organizar um estudo sobre como podemos utilizar o framework Scrapy para automatizar a pesquisa em todos os Diários Oficiais. O Scrapy é uma ferramenta de web scraping em Python que pode ser útil para coletar informações de fontes web como os Diários Oficiais.

Passos:

- [x] Realizar uma pesquisa para entender o que é o Scrapy e como ele pode ser usado para a coleta de informações em páginas da web.
- [x]  Coletar recursos, tutoriais e documentação relacionados ao Scrapy.
- [x]  Identificar os Diários Oficiais que desejamos pesquisar.
- [x] Analisar a estrutura das páginas web desses Diários Oficiais.
- [x]  Instalar o Scrapy e configurar o ambiente de desenvolvimento.
- [x] Realizar reuniões regulares para discutir o progresso do estudo do Scrapy e quaisquer desafios encontrados.
- [ ]

**Comment by gio221** [comment]
Eu pesquisei e estudei um pouco o uso do scrapy

**Comment by RafaBonach** [comment]
Não consegui estudar tanto o scrapy mas dei algumas ideias de funcionalidades que poderíamos colocar em nosso projeto.

**Comment by juliatakaki** [comment]
Dei ideias sobre como poderíamos fazer com que o nosso projeto fosse menos abrangente.

**Comment by samarawwleticia** [comment]
Pesquisei no youtube maneiras de fazer o nosso projeto automatico.
