### ISSUE TITLE
Estudo da Pesquisa de Licitação no Diário Oficial

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#68]
Descrição:
Essa issue foi criada com o objetivo do grupo se reunir e também pensar individualmente como vamos melhorar na nossa pesquisa no Diário Oficial

Tarefas:

- [x] Ver todos os Diários Oficiais do estado do Ceará
- [x] Pensar uma forma de a pesquisa ser mais detalhada 
- [x] Estudar como o scrap poderia ajudar nessa pesquisa detalhada

**Comment by gio221** [comment]
Eu pesquisei nos Diários Oficiais sobre licitação

**Comment by RafaBonach** [comment]
Sugeri algumas possíveis funcionalidades que caberiam ao nosso projeto seguindo a ideia do Querido Diário de realizar a pesquisa por palavras e apresentar o trecho no texto que apresenta a palavra licitação

**Comment by juliatakaki** [comment]
Pesquisei e discutimos sobre possíveis implementações no projeto.

**Comment by samarawwleticia** [comment]
Procurei nos Diarios Oficiais um tema de licitação para usarmos no nosso projeto.
