### ISSUE TITLE
Estudo do Coalize como Contabilizador de Horas para o Projeto

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#7]
Descrição:

Essta issue tem como objetivo realizar um estudo aprofundado sobre como usar o Coalize como uma ferramenta para contabilizar as horas dedicadas ao projeto. A contabilização precisa das horas é essencial para medir o progresso do projeto, alocar recursos de forma eficiente e garantir que as metas de prazo sejam atingidas. Esta tarefa visa investigar e entender como o Coalize pode ser configurado e utilizado para este fim.

Tarefas a serem realizadas:

- [x] Pesquisa Inicial: Realizar uma pesquisa para entender as funcionalidades do Coalize relacionadas à contabilização de horas

- [x] Configuração Inicial: Configurar uma conta ou espaço de trabalho no Coalize dedicado ao projeto

- [x] Treinamento e Uso: Explorar as funcionalidades do Coalize para registrar horas trabalhadas em tarefas e projetos

- [x] Baixar o aplicativo e aprender a contabilizar as horas

**Comment by samarawwleticia** [comment]
achei no coalize uma planilha de controle de ponto gratuita que a gente vai poder usar

**Comment by gio221** [comment]
Definimos o clockify como contabilizador de horas para o projeto
