### ISSUE TITLE
 Desenvolvimento Front-end para deixar mais fiel ao prototipo

### ISSUE THREAD

**Issue by gio221** [unb-mds/2023-2-Squad07#80]
Descrição

Esta issue destina-se ao planejamento e execução do desenvolvimento front-end, visando aprimorar a experiência do usuário em nossa aplicação. O front-end desempenha um papel crucial na interação do usuário com o sistema, e nosso objetivo é garantir uma interface intuitiva, responsiva e agradável.

Tarefas:

- [x] Realizar uma revisão da interface atual da aplicação.
- [x] Identificar áreas de melhoria com base no feedback do usuário e nas tendências de design.
- [x] Avaliar as tecnologias e ferramentas mais recentes para o desenvolvimento front-end.
- [x] Realizar modificações para ficar fiel ao prototipo
- [x] Identificar e resolver quaisquer problemas de desempenho 
- [x] Explorar a criação e utilização de componentes reutilizáveis para promover consistência no design e na funcionalidade.
- [x] Implementar testes front-end para garantir a estabilidade e a qualidade do código.

**Comment by gio221** [comment]
Desenvolvi o front-end fiel ao prototipo

**Comment by juliatakaki** [comment]
fiz o código do rodapé; está em outra issue.
